### ISSUE TITLE
【メッセージ画面】-【View】-一瞬だけEmpty Stateになる

### ISSUE THREAD

**Issue by obaya884** [shun-shun123/tapiten_app#61]
## 目的
既に質問／回答実績があっても読み込みが非同期のため反映されるまでEmpty Stateの表示になってしまう問題を解消する

## TaskList
+ [ ] 

## Doneの定義
読み込み時にEmpty Stateが表示されない

## 参考
![instant_empty_state](https://user-images.githubusercontent.com/38175830/92690630-48237900-f37c-11ea-9f78-e6cf4ebfcd08.gif)

## 留意事項
- 現状なし

## 検討事項
- 現状なし

**Comment by shun-shun123** [comment]
closed by #76
